import = ["~/.config/alacritty/themes/ayu_mirrage.toml"]

[window]
opacity = 1

[window.padding]
x = 0
y = 0

[shell]
program = "/bin/zsh"

[font]
size = 14

[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
action = "ScrollPageDown"

[scrolling]
history = 10_000

[env]
TERM = "xterm-256color"
