import:
    - ~/.config/alacritty/themes/ayu_mirrage.yml
window:
    opacity: 1
    padding:
        x: 0
        'y': 0
shell:
  program: /bin/zsh
font:
    size: 10
    normal:
        family: JetBrains Mono
        style: Regular
    bold:
        family: JetBrains Mono
        style: Bold
    italic:
        family: JetBrains Mono
        style: Italic
key_bindings:
    -
        key: K
        mods: Control|Shift
        action: ScrollPageUp
    -
        key: J
        mods: Control|Shift
        action: ScrollPageDown
scrolling:
    history: 10000
env:
    TERM: xterm-256color

